### ISSUE TITLE
Request: add descriptions to the buffs from devour, please

### ISSUE THREAD

**Issue by OromisElf** [Ethanol10/rimuru-tempest-ror2#2]
Enjoying your mod a lot so far, and I know it's technically not in development anymore but could you please add descriptions to when one is hovering the buff icons? I don't know what strengthen body does ;_;

**Comment by Ethanol10** [comment]
Hi there,

Glad you're enjoying the mod! Sorry Im not able to add descriptions to buff icons in game, as that information is not allowed to be added into the game. 

Later down the line we do wish to update the mod to include more buff types from various different enemies, instead of generic types.

For strengthenn body, I do believe it's a straight damage buff.

**Comment by OromisElf** [comment]
oh, yeah it was
In the heat of the battle I wasn't looking properly :D
thanks for the fast reply and shame about the buff description
have a great day o/

**Comment by OromisElf** [comment]
oh, yeah it was
In the heat of the battle I wasn't looking properly :D
thanks for the fast reply and shame about the buff description
have a great day o/
